Update 1-assign-yourself.yml

diff --git a/.github/workflows/1-assign-yourself.yml b/.github/workflows/1-assign-yourself.yml
--- a/.github/workflows/1-assign-yourself.yml
+++ b/.github/workflows/1-assign-yourself.yml
@@ -39,12 +39,63 @@ jobs:
           fetch-depth: 0 # Let's get all the branches
           ref: update-game
 
-      # Update README to close <details id=1> and open <details id=2>
-      # and set STEP to '2'
-      - name: Update to step 2
-        uses: skills/action-update-step@v1
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          from_step: 1
-          to_step: 2
-          branch_name: update-game
+      - name: Update step
+        run: |
+          echo "Check that all required env variables are set"
+          if [ -z "$TO_STEP" ]
+          then
+            echo "TO_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$FROM_STEP" ]
+          then
+            echo "FROM_STEP is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$GITHUB_TOKEN" ]
+          then
+            echo "GITHUB_TOKEN is unset or set to the empty string"
+            exit 1
+          fi
+          echo "Make sure we are on the base branch ($BASE_BRANCH_NAME)"
+          git checkout $BASE_BRANCH_NAME
+          echo "Check that we are on FROM_STEP"
+          if [ "$(cat .github/script/STEP)" != $FROM_STEP ]
+          then
+            echo "Current step is not $FROM_STEP"
+            exit 0
+          fi
+          echo "Remove 'open' from any <details> tags"
+          sed -i.tmp -r 's/<details id=([0-9X]+) open>/<details id=\1>/g' README.md
+          echo "Add 'open' to step TO_STEP"
+          sed -i.tmp -r "s/<details id=$TO_STEP>/<details id=$TO_STEP open>/g" README.md
+          echo "Update all HTML comments to hide everything"
+          sed -i.tmp -r 's/<!--step([0-9X]+)-->/<!--step\1/g' README.md
+          sed -i.tmp -r 's/<!--endstep([0-9X]+)-->/endstep\1-->/g' README.md
+          echo "Show the current TO_STEP"
+          sed -i.tmp -r "s/<\!--step$TO_STEP/<\!--step$TO_STEP-->/g" README.md
+          sed -i.tmp -r "s/endstep$TO_STEP-->/<\!--endstep$TO_STEP-->/g" README.md
+          echo "Update the STEP file to TO_STEP"
+          echo "$TO_STEP" > .github/script/STEP
+          echo "Commit the files, and push to base branch"
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add README.md
+          git add .github/script/STEP
+          git commit --message="Update to $TO_STEP in STEP and README.md"
+          git push
+          echo "If BRANCH_NAME, update that branch as well"
+          if git show-ref --quiet refs/heads/$BRANCH_NAME
+          then
+            git checkout $BRANCH_NAME
+            COMMIT_ID=$(git rev-parse main)
+            git cherry-pick $COMMIT_ID
+            git push
+          else
+            echo "Branch $BRANCH_NAME does not exist"
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          FROM_STEP: 1
+          TO_STEP: 2
+          BRANCH_NAME: "update-game"
